name: Deploy App 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - cicd
jobs:
  Testing-Connection:
    runs-on: self-hosted
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
        
       - name: Testing the connection
         run: pwd && whoami && hostname
        
       - name: Docker Login
         uses: docker/login-action@v3.1.0
         with:
            # Server address of Docker registry. If not set then will default to Docker Hub
            # registry: 
            # Username used to log against the Docker registry
            username: ${{ secrets.DOCKER_USERNAME }}
            # Password or personal access token used to log against the Docker registry
            password: ${{ secrets.DOCKER_PASS }}
            # Log out from the Docker registry at the end of a job
            logout: true
     
