name: Deploy App 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - cicd
jobs:
  Testing-Connection:
    runs-on: self-hosted
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
        
       - name: Testing the connection
         run: pwd && whoami && hostname
        
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
