name: Docker Build & Push 
run-name: Docker Build and Push
on:
  push:
    branches:
      - cicd
jobs:
  Docker-Build:
    runs-on: self-hosted
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
        
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and push Docker images
         uses: docker/build-push-action@v1.1.0
         with:
           username: ${{ secrets.DOCKEHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          # Docker repository to tag the image with
           repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DEPLOY_IMAGE }}:latest
          # Path to the build context
           path: backend
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
           dockerfile: backend/Dockerfile
          # Whether to push the image
           push: true
                
                  
