name: MERN App CI

on:
  push:
    branches:
      - 'ci*'

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - run: npm run build --if-present
      - run: npm test
